feat(login): Service, login page, notifier added
DUT-Info-Montreuil/SAE-5.A-CarMate-Front pull request #1
Opened 2023-11-04 19:13 UTC by almerion

### What was done: 
- Added login page & component 
- Added a notifier dependency 
- Added AutenticationService and a login function
- Added FontAwesome for the icons

2023-11-05 17:24 UTC, naulan-chrzaszcz reviewed
Je connais rien en TypeScript donc le review est probablement trés superficiel

2023-11-05 17:24 UTC, naulan-chrzaszcz commented on src/app/service/user/authentication/authentication.service.ts
> +    );
Ceci converti les données renvoyé par l'API en une interface `Token` ?
Le truc c'est si il y a plus d'une valeurs dans le json de retour, genre un truc comme ca :
```json
{
    "token": "êzjfuizbfiaezĵhro_yéç_uazhqpe_çfhé",
    "expiration": "2001-01-01",
    "user": 3
}
```
Est-ce qu'il va fonctionner ? 
J'ai 0 experience en typescript donc jpeux dire full merde

2023-11-05 17:27 UTC, naulan-chrzaszcz commented on src/app/service/user/authentication/authentication.service.ts
> +    );
`localStorage.setItem('auth_token', token.token);` Et pour ca, il y a pas des conventions ou quelque chose du genre ?

2023-11-06 18:34 UTC, almerion commented on src/app/service/user/authentication/authentication.service.ts
> +    );
ça marchera toujours, même s'il sera préférable de mettre à jour l'interface.

Pour le token franchement tant qu'il est stocké dans le local storage ou dans les cookies c'est bon, enfin il faudrait peut-être que je le mette plustot dans les cookies idk

2023-11-11 20:30 UTC, almerion commented on src/app/service/user/authentication/authentication.service.ts
> +    );
Finalement il reste dans le localstorage, on le mettera dans les cookies plus tard si nécessaire

2023-11-13 09:10 UTC, naulan-chrzaszcz commented
Je vais faire mon relou, mais... Tu peux mettre tes jeux de tests dans un commit à part ?
Qu'est-ce que t'en pense ?

2023-11-13 09:14 UTC, naulan-chrzaszcz approved these changes
Je certifie avec mes faible connaissances en Angular
![sueur](https://image.noelshack.com/fichiers/2018/10/1/1520256134-risitasue2.png)

2023-11-13 19:37 UTC, ayman-75 reviewed
ton code à l'air très clean , mon bon, mon niveau en ts et angular et pas ouf pour l'instant donc mon avis n'est pas intéressant mais c propre

2023-11-13 21:52 UTC, naulan-chrzaszcz requested changes

2023-11-14 19:01 UTC, almerion commented on src/app/layout/user/login/login.component.ts
> +      }
C'est changé, je tiens à préciser que je n'avais pas inventé les erreus mais c'était celles du doc *

2023-11-14 22:37 UTC, naulan-chrzaszcz requested changes
Renomme ton commit aussi au passage par `feat(login): Service, login page, notifier added - UC-34` pour exploiter la fonctionnalité autolink reference de Github

2023-11-14 22:37 UTC, naulan-chrzaszcz commented on src/app/layout/user/login/login.component.spec.ts
> +    component["loginForm"].controls.password.setValue(testUser.password);
Je fois plusieurs fois ce bout de code, est-ce que une fonction sera pas mieux pour simplifier le code ?

2023-11-14 22:37 UTC, naulan-chrzaszcz commented on src/app/layout/user/login/login.component.spec.ts
> +    const testUser = {email: "test@example.com", password: 'password123'}
Tu peux pas le mettre en tant que variable global ?

2023-11-14 22:37 UTC, naulan-chrzaszcz commented on src/app/layout/user/login/login.component.spec.ts
> +    const testUser = {email: "test@example.com", password: 'password123'}
(Pour ceux qui sont les même)

2023-11-15 07:14 UTC, naulan-chrzaszcz approved these changes
LGTM 🚀🚀🚀

2023-11-15 07:29 UTC, merged