feat(reserve-carpool): search for carpool - UC-40
DUT-Info-Montreuil/SAE-5.A-carmate-front pull request #12
Opened 2023-12-13 20:21 UTC by LiberiBg

2023-12-13 20:46 UTC, naulan-chrzaszcz commented on src/app/layout/search-bar/search-bar.component.ts
> +    this.carpoolingService.search(payload);
Tu regarde pas si la requête a fonctionné ?

2023-12-13 20:46 UTC, naulan-chrzaszcz commented on src/app/layout/search-bar/search-bar.component.ts
> +      departure_date_time: Math.floor(dateStart.getTime() / 1000)
Ce bout de code met la date en format timestamp unix ? 

https://www.unixtimestamp.com/

2023-12-13 20:49 UTC, LiberiBg commented on src/app/layout/root/root.component.spec.ts
Correction d'un fail de ma part

2023-12-13 20:50 UTC, LiberiBg commented on src/app/layout/search-bar/search-bar.component.ts
> +      departure_date_time: Math.floor(dateStart.getTime() / 1000)
yes cf le screen que je t'ai envoyé sur discord, ça convertit la date en seconde depuis 1970

2023-12-15 13:35 UTC, LiberiBg commented on src/app/layout/search-bar/search-bar.component.ts
> +    this.carpoolingService.search(payload);
requête good

2023-12-15 15:17 UTC, naulan-chrzaszcz requested changes
Les choses a revoir:
- Enlever le split sur string lat;lon
- Renommer le route `/carpooling/create` => `/carpooling`
- D'autre trucs

2023-12-15 15:17 UTC, naulan-chrzaszcz commented on src/app/layout/search-bar/search-bar.component.ts
> +  private starting_coords: string = '';
```suggestion
  private starting_coords: number[] = [];
```

2023-12-15 15:17 UTC, naulan-chrzaszcz commented on src/app/layout/search-bar/search-bar.component.ts
> +
```suggestion
    this.starting_coords = [lat, lon];
```

2023-12-15 15:17 UTC, naulan-chrzaszcz commented on src/app/layout/search-bar/search-bar.component.ts
> +
```suggestion
    this.starting_coords = [lat, lon];
```

2023-12-15 15:17 UTC, naulan-chrzaszcz commented on src/app/layout/search-bar/search-bar.component.ts
> +    const [end_lat, end_lon] = this.destination_coords.split(';')
```suggestion
    const [start_lat, start_lon] = this.starting_coords
    const [end_lat, end_lon] = this.destination_coords
```

2023-12-15 15:17 UTC, naulan-chrzaszcz commented on src/app/layout/search-bar/search-bar.component.ts
> +            break;
La search bar est publique

2023-12-15 15:17 UTC, naulan-chrzaszcz commented on src/app/layout/search-bar/search-bar.component.ts
> +            break;
```suggestion
        switch (error.status) {
          case 400:
            this.notifier.error("Un ou plusieurs champs sont invalides.");
            break;
          case 503:
            this.notifier.error("Service momentanément indisponible.");
            break;
          default:
            this.notifier.error("Erreur interne.");
            break;
```

2023-12-15 15:17 UTC, naulan-chrzaszcz commented on src/app/service/carpooling/carpooling.service.mock.ts
> +  }
La filtre sur le date de départ n'est pas fait

2023-12-15 15:17 UTC, naulan-chrzaszcz commented on src/app/service/carpooling/carpooling.service.ts
> +    return this.http.post<Carpooling>(`${environment.path}/carpooling/create`, carpooling);
```suggestion
    return this.http.post<Carpooling>(`${environment.path}/carpooling`, carpooling);
```

2023-12-15 15:33 UTC, LiberiBg commented on src/app/service/carpooling/carpooling.service.ts
> +    return this.http.post<Carpooling>(`${environment.path}/carpooling/create`, carpooling);
non

2023-12-18 18:04 UTC, naulan-chrzaszcz requested changes
Code style et une fonction qui est utilisé qu'une seul fois dans le composant

2023-12-20 10:28 UTC, naulan-chrzaszcz approved these changes
LGTM !!!!!!!!!!!!!!!!!!!!! 🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀

2023-12-20 11:07 UTC, merged