feat(publish-carpool): add tests
DUT-Info-Montreuil/SAE-5.A-carmate-front pull request #19
Opened 2023-12-20 01:35 UTC by LiberiBg

2023-12-20 08:43 UTC, naulan-chrzaszcz requested changes
Un id à renommer (le mettre en snake case)
Et une question sur les passagers Max dans le formulaire

2023-12-20 08:43 UTC, naulan-chrzaszcz commented on src/app/layout/publish-carpool/publish-carpool.component.html
> +            <input matInput required formControlName="departure_date" [matDatepicker]="picker" id="dateDeparture_id"  [matDatepickerFilter]="dateFilter">
```suggestion
            <input matInput required formControlName="departure_date" [matDatepicker]="picker" id="date_departure_id"  [matDatepickerFilter]="dateFilter">
```
Pour que ça soit homogène avec les autres id's

2023-12-20 08:43 UTC, naulan-chrzaszcz commented on src/app/layout/publish-carpool/publish-carpool.component.spec.ts
> +    const button = fixture.debugElement.query(By.css('#dateDeparture_id')).nativeElement;
```suggestion
    const button = fixture.debugElement.query(By.css('#date_departure_id')).nativeElement;
```

2023-12-20 08:43 UTC, naulan-chrzaszcz commented on src/app/layout/publish-carpool/publish-carpool.component.spec.ts
> +      .toBeTruthy();
Là avec ton formulaire, on peut uniquement mettre 4 passagers ? 
T'es sur qu'on laisse comme ça ?

2023-12-20 11:11 UTC, LiberiBg commented on src/app/layout/publish-carpool/publish-carpool.component.spec.ts
> +      .toBeTruthy();
Tu proposes quoi sinon entre 1 et 4

2023-12-23 16:46 UTC, LiberiBg commented
Ho la galère sur git mais au moins c'est good

2023-12-23 17:47 UTC, naulan-chrzaszcz requested changes
Une simplification a faire

2023-12-23 17:47 UTC, naulan-chrzaszcz commented on src/app/layout/publish-carpool/publish-carpool.component.spec.ts
> +    const button = fixture.debugElement.query(By.css('#publish_id')).nativeElement;
Je vois beaucoup de fois la variable `button` déclaré dans les tests, il y a pas moyen de le mettre dans le `beforeEach` ?

2023-12-23 18:06 UTC, LiberiBg commented on src/app/layout/publish-carpool/publish-carpool.component.spec.ts
> +    const button = fixture.debugElement.query(By.css('#publish_id')).nativeElement;
J'viens d'essayer ça casse les tests

2023-12-28 21:49 UTC, naulan-chrzaszcz approved these changes
LGTM 🚀🚀 🚀 🚀 🚀 🚀

2024-01-05 17:17 UTC, LiberiBg commented
Le rebase de develop a casser un test, je fix plus tard

2024-01-06 00:33 UTC, merged