feat(reserve-carpooling): displays carpooling result - UC-40
DUT-Info-Montreuil/SAE-5.A-carmate-front pull request #22
Opened 2023-12-23 14:12 UTC by LiberiBg

2023-12-23 14:16 UTC, LiberiBg commented on angular.json
Après avoir finaliser les modifs sur le commit 'WIP', cette modif sera dans un commit à part

2023-12-28 09:52 UTC, almerion requested changes
nickel, quelques petites suggestions mais sinon c'est good

2023-12-28 09:52 UTC, almerion commented on src/app/interface/carpooling.ts
> +    search: (search: Search) => void;
l'api renvoie une liste de carpooling, il faut pas laisser void je pense, ça a été mis à cause du mock ?

2023-12-28 09:52 UTC, almerion commented on src/app/layout/carpooling/carpooling.component.spec.ts
> +        {provide: CARPOOLING_SERVICE_TOKEN, useValue: spyCarpoolingService},
```suggestion
```
Le component n'a besoin que du adress_service

2023-12-28 09:52 UTC, almerion commented on src/app/layout/carpooling/carpooling.component.spec.ts
> +    component.ngOnInit();
```suggestion
```
Déjà déclaré et fait dans le beforeEach

2023-12-28 09:52 UTC, almerion commented on src/app/layout/carpooling/carpooling.component.ts
> +    let matchingSchoolDestination = this.addressService.$schoolList.find(school =>
Plutôt que forcer un find dans la liste du service, je pense que ce serait mieux d'avoir une fonction dans le service qui fait la recherche en lui passant les starting point, la les contexte du service et du component sont entrain de se mélanger

2023-12-28 09:52 UTC, almerion commented on src/app/layout/carpooling/carpooling.component.ts
> +    let matchingSchoolDestination = this.addressService.$schoolList.find(school =>
enfin c'est une proposition

2023-12-28 09:52 UTC, almerion commented on src/app/layout/result-carpool/result-carpool.component.scss
> +}
Tu peux décaler ça dans tailwind je crois avec `h-[calc(100vh-20vh)]`

2023-12-28 09:52 UTC, almerion commented on src/styles.scss
> +@import 'ol/ol.css';
Ol c'est bien pour la map ? 
Si c'est que pour la map il faut pas importer le style sur toutes les pages, ça alourdit le css, si y'a moyen de déplacer ça selement dans le component ou on a besoin de ce css ce serait parfait sinon si on en a besoin globalement laisse le ici

2023-12-28 09:53 UTC, almerion commented on src/app/interface/carpooling.ts
> +    search: (search: Search) => void;
nevermind le comportement a change du coup

2023-12-28 16:42 UTC, LiberiBg commented on src/app/layout/carpooling/carpooling.component.ts
> +    let matchingSchoolDestination = this.addressService.$schoolList.find(school =>
good idea

2023-12-28 16:52 UTC, LiberiBg commented on src/styles.scss
> +@import 'ol/ol.css';
J'ai déjà essayé j'pense pas qu'on puisse

2023-12-28 17:04 UTC, LiberiBg commented
Manque l'implémentation correcte de l'api (je récupère l'ensemble de la réponse api plutôt que la liste de covoiturage)

2023-12-28 21:31 UTC, LiberiBg commented
Implémentation de l'API good, à tester en prod

2023-12-29 15:55 UTC, naulan-chrzaszcz requested changes
Simplification de condition et code style

2023-12-29 15:55 UTC, naulan-chrzaszcz commented on src/app/layout/carpooling/carpooling.component.spec.ts
> +    });
```suggestion
spyAddressService.matchingSchoolDeparture.and.callFake((lat: number, lon: number): string | undefined => 
  spyAddressService.$schoolList.find(school => school.lat === lat && school.lon === lon)?.name
);
```
A tester (j'suis pas sûr)

2023-12-29 15:55 UTC, naulan-chrzaszcz commented on src/app/layout/map/map.component.ts
> +    }
Tu peux simplifié avec une condition ternaire

2023-12-29 15:59 UTC, LiberiBg commented on src/app/layout/carpooling/carpooling.component.spec.ts
> +      ]
Y'aura aucun autre component dans les déclarations, on peut garder ça sur une seule ligne ?

2023-12-29 17:24 UTC, LiberiBg commented on src/app/layout/carpooling/carpooling.component.spec.ts
> +      ]
+  il est écrit sur une ligne comme dans tous les autres fichiers

2023-12-29 18:24 UTC, naulan-chrzaszcz commented on src/app/layout/carpooling/carpooling.component.spec.ts
> +      ]
Le code style est a revoir mais si c'est comme ca dans tous les fichiers, go laissé comme ca

2023-12-29 18:25 UTC, naulan-chrzaszcz approved these changes
(Attend la review de @almerion pour que ta PR soit parfaite)
LGTM 🚀🚀🚀🚀🚀🚀🚀🚀🚀

2023-12-29 20:09 UTC, almerion approved these changes
LGTM 🚀🚀🚀🚀

2023-12-29 20:21 UTC, merged