Feature(create-subscription): user create subscription to regular carpooling
DUT-Info-Montreuil/SAE-5.A-carmate-front pull request #25
Opened 2024-01-05 17:06 UTC by LiberiBg

2024-01-05 21:27 UTC, almerion requested changes
juste l'histoire des jours, sinon tout m'a l'air good

2024-01-05 21:27 UTC, almerion commented on src/app/layout/create-subscription/create-subscription.component.html
> +            <input matInput formControlName="label" placeholder="Aller tous les lundi et maardi du S1">
```suggestion
            <input matInput formControlName="label" placeholder="Aller tous les lundi et mardi du S1">
```

2024-01-05 21:27 UTC, almerion commented on src/app/layout/create-subscription/create-subscription.component.ts
> +  protected readonly days = ['Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi'];
Au niveau des jours on peut garder ça pour l'affichage mais il faut mapper aux noms anglais pour l'api :s

2024-01-06 00:11 UTC, LiberiBg commented on src/app/interface/carpooling.ts
> +    days: string[];
Yes bonne idée

2024-01-06 00:27 UTC, LiberiBg commented
> juste l'histoire des jours, sinon tout m'a l'air good

Good

2024-01-06 21:23 UTC, LiberiBg commented
Le bouton d'envoi de formulaire est activé par défaut, le code pour le désactiver si les champs sont incomplets est toujours là mais  ça empêche le clique dessus lors du dernier test unitaire qui remplis plusieurs fois le form si quelqu'un a une solution??.???..?

2024-01-07 22:25 UTC, LiberiBg commented
Prêt à être reviewed

2024-01-08 11:07 UTC, naulan-chrzaszcz reviewed
J'ai juste regardé le code

2024-01-08 11:07 UTC, naulan-chrzaszcz commented on src/app/interface/carpooling.ts
> +export type WeekDay = "Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday";
```suggestion
export type WeekDay = "Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday" | "Saturday" | "Sunday";
```

2024-01-08 11:19 UTC, almerion approved these changes
LGTM !!!🚀🚀🚀🚀🚀🚀

2024-01-09 00:34 UTC, LiberiBg commented on src/app/interface/carpooling.ts
> +export type WeekDay = "Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday";
On traite aucune données qui peuvent être le weekend normalement

2024-01-09 12:54 UTC, naulan-chrzaszcz commented on src/app/interface/carpooling.ts
> +export type WeekDay = "Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday";
Ouaip j'ai vu que le code n'utilise pas le weekend mais part rapport a la DB, il y a le weekend
Si tu veux faire un truc qui est identique a la DB, tu peux le mettre sinon skip cette suggestion

2024-01-09 12:54 UTC, naulan-chrzaszcz commented on src/app/interface/carpooling.ts
> +export type WeekDay = "Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday";
(Vu que c'est un type)

2024-01-09 12:56 UTC, naulan-chrzaszcz approved these changes
LGTM MGL !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀

2024-01-09 16:53 UTC, merged