feat(register) : register form - UC - 33
DUT-Info-Montreuil/SAE-5.A-CarMate-Front pull request #3
Opened 2023-11-20 17:52 UTC by ayman-75

2023-11-21 09:33 UTC, naulan-chrzaszcz commented
![ah-shit-here-we-go-again-ah-shit](https://github.com/DUT-Info-Montreuil/SAE-5.A-CarMate-Front/assets/67024770/acbbd041-8924-4806-84d7-bc8d2dd08d78)
Ton commit est mal ecrit

2023-11-21 09:36 UTC, naulan-chrzaszcz commented
![image](https://github.com/DUT-Info-Montreuil/SAE-5.A-CarMate-Front/assets/67024770/2f15314e-c97e-44e7-845a-2f681b81c932)
Enlève @jhrety dans les reviewers, c'est un prof... Pas un membre de l'équipe de notre SAE 😢

2023-11-21 09:48 UTC, naulan-chrzaszcz requested changes
Des espaces partout voir en trop pour je ne sais quel raison, faut que tu corrige ça.
Revoir les noms des arguments `academicYear0` et `academicYear1`

Vu que ta refait une PR, je ne peux pas voir facilement ce que ta corriger ou non... Donc on va dire qu'il y a jamais eu de review (it is what it is)

2023-11-21 09:48 UTC, naulan-chrzaszcz commented on src/app/app-routing.module.ts
> +
Pourquoi autant d'espace ?

2023-11-21 09:48 UTC, naulan-chrzaszcz commented on src/app/interface/user.ts
> +  register: (firstName: string, lastName: string, email: string, password: string, accountType: string,  document: File,  academicYear0?: string, academicYear1?: string) => Observable<any>;
Essaye plutôt academicYearStart academicYearEnd

2023-11-21 09:48 UTC, naulan-chrzaszcz commented on src/app/layout/user/register/register.component.html
> +    </div>
Revoir les nom des label etc du a mon précèdent commentaire

2023-11-21 09:48 UTC, naulan-chrzaszcz commented on src/app/layout/user/register/register.component.ts
> +
J'ai l'impression que c'est du troll

2023-11-21 09:48 UTC, naulan-chrzaszcz commented on src/app/layout/user/register/register.component.ts
> +    const academicYear1 = this.registerForm.get('academicYear1')?.value;
pareil, revoir le nom

2023-11-21 09:51 UTC, naulan-chrzaszcz commented
Pour coller a ce que a fait @almerion tu peux rename ton commit par `feat(register): register page - UC-33`

2023-11-23 09:09 UTC, naulan-chrzaszcz requested changes
J'ai certain doute sur le fait que le code soit généré par ChatGPT dû au commentaire inutile au debut et aussi un peut partout dans le code
La vérification du mot de passe doit être revu
Du code style appliquer a la volé dans le code qui allourdis le commit
Tu as toucher du code qui t'appartient pas dans ton commit, corrige ca

2023-11-23 09:09 UTC, naulan-chrzaszcz commented on src/app/app-routing.module.ts
> +
Enlève l'espace

2023-11-23 09:09 UTC, naulan-chrzaszcz commented on src/app/app-routing.module.ts
> +    },
Deux fois register ?

2023-11-23 09:09 UTC, naulan-chrzaszcz commented on src/app/interface/user.ts
>  export const AUTHENTICATION_SERVICE_TOKEN = new InjectionToken<AuthenticationServiceInterface>('AuthenticationServiceInterface');
ChatGPT ?

2023-11-23 09:09 UTC, naulan-chrzaszcz commented on src/app/layout/user/login/login.component.html
> +        <fa-icon [icon]="faEnvelope" id="envelope-icon"></fa-icon>
Ce n'est pas ton code, tu ne doit pas le toucher

2023-11-23 09:09 UTC, naulan-chrzaszcz commented on src/app/layout/user/login/login.component.ts
> -    // Reset api error for the IHM on input change
Pourquoi ?

2023-11-29 10:51 UTC, naulan-chrzaszcz approved these changes
LGTM 🚀 🚀 🚀

2023-11-29 11:36 UTC, almerion approved these changes
LGTM !! 🚀:rocket:

2023-11-29 11:36 UTC, merged